# Generated by Django 5.2.4 on 2025-07-30 14:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', '男性'), ('female', '女性')], max_length=6)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', '男性'), ('female', '女性')], max_length=6)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6)])),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(choices=[('primary_1', '小学１年生'), ('primary_2', '小学２年生'), ('primary_3', '小学３年生'), ('primary_4', '小学４年生'), ('primary_5', '小学５年生'), ('primary_6', '小学６年生'), ('junior_1', '中学１年生'), ('junior_2', '中学２年生'), ('junior_3', '中学３年生'), ('senior_1', '高校１年生'), ('senior_2', '高校２年生'), ('senior_3', '高校３年生'), ('graduate', '既卒')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='personal_info.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', '男性'), ('female', '女性')], max_length=6)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(choices=[('college_1', '大学１年生'), ('college_2', '大学２年生'), ('college_3', '大学３年生'), ('college_4', '大学４年生'), ('working_adult', '社会人')])),
                ('subjects', models.ManyToManyField(blank=True, to='personal_info.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='授業日')),
                ('start_time', models.TimeField(verbose_name='授業開始時刻')),
                ('end_time', models.TimeField(verbose_name='授業終了時刻')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確定')),
                ('is_pending', models.BooleanField(default=True, verbose_name='保留')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.teacherprofile')),
            ],
        ),
    ]
