# Generated by Django 5.2.4 on 2025-07-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='date',
            new_name='class_date',
        ),
    ]
