# Generated by Django 5.2.4 on 2025-08-01 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_rename_date_classschedule_class_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='karte_detail',
            field=models.TextField(blank=True, verbose_name='授業内容詳細'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='karte_summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='授業概要'),
        ),
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='教材名')),
                ('grade', models.CharField(blank=True, choices=[('primary_1', '小学１年生'), ('primary_2', '小学２年生'), ('primary_3', '小学３年生'), ('primary_4', '小学４年生'), ('primary_5', '小学５年生'), ('primary_6', '小学６年生'), ('junior_1', '中学１年生'), ('junior_2', '中学２年生'), ('junior_3', '中学３年生'), ('senior_1', '高校１年生'), ('senior_2', '高校２年生'), ('senior_3', '高校３年生'), ('graduate', '既卒')], verbose_name='推奨学年')),
                ('description', models.TextField(blank=True, verbose_name='説明（空欄可）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='教材情報登録月日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教材情報登録者')),
                ('subject', models.ManyToManyField(to='personal_info.subject', verbose_name='科目名')),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.teachingmaterial'),
        ),
    ]
