# Generated by Django 5.2.4 on 2025-08-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_classschedule_karte_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.teachingmaterial', verbose_name='使用教材'),
        ),
        migrations.RemoveField(
            model_name='teachingmaterial',
            name='subject',
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.teachingmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='teachingmaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.subject', verbose_name='関連科目'),
        ),
    ]
