# Generated by Django 5.2.4 on 2025-08-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0004_alter_classschedule_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('elementary', '小学生'), ('junior', '中学生'), ('high', '高校生'), ('custom', '金額自由設定')], max_length=20, unique=True)),
                ('reward_per_class', models.IntegerField(blank=True, null=True, verbose_name='１コマ当たりの報酬額')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='billing_per_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='生徒への請求額（１コマ）'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='custom_reward_per_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='自由報酬額（１コマ）'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(choices=[('elementary_1', '小学１年生'), ('elementary_2', '小学２年生'), ('elementary_3', '小学３年生'), ('elementary_4', '小学４年生'), ('elementary_5', '小学５年生'), ('elementary_6', '小学６年生'), ('junior_1', '中学１年生'), ('junior_2', '中学２年生'), ('junior_3', '中学３年生'), ('senior_1', '高校１年生'), ('senior_2', '高校２年生'), ('senior_3', '高校３年生'), ('graduate', '既卒')]),
        ),
        migrations.AlterField(
            model_name='teachingmaterial',
            name='grade',
            field=models.CharField(blank=True, choices=[('elementary_1', '小学１年生'), ('elementary_2', '小学２年生'), ('elementary_3', '小学３年生'), ('elementary_4', '小学４年生'), ('elementary_5', '小学５年生'), ('elementary_6', '小学６年生'), ('junior_1', '中学１年生'), ('junior_2', '中学２年生'), ('junior_3', '中学３年生'), ('senior_1', '高校１年生'), ('senior_2', '高校２年生'), ('senior_3', '高校３年生'), ('graduate', '既卒')], verbose_name='推奨学年'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reward_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.rewardcategory', verbose_name='報酬区分（講師向け）'),
        ),
    ]
