# Generated by Django 5.2.4 on 2025-08-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0005_rewardcategory_studentprofile_billing_per_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassKarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(verbose_name='授業日')),
                ('karte_summary', models.CharField(max_length=200, verbose_name='授業概要')),
                ('karte_detail', models.TextField(blank=True, verbose_name='授業内容詳細')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.teachingmaterial', verbose_name='使用教材')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_info.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.teacherprofile')),
            ],
        ),
    ]
