# Generated by Django 5.2.4 on 2025-08-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0006_classkarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='classkarte',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karte', to='personal_info.classschedule'),
        ),
    ]
