# Generated by Django 5.2.4 on 2025-08-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0009_classkarte_evaluation_classkarte_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcategory',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='区分名（例：小学生/中学生/高校生/中学受験 など）'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='reward_per_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='１コマ当たりの報酬額（円）'),
        ),
    ]
