# Generated by Django 5.2.4 on 2025-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0010_alter_rewardcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcategory',
            name='category',
            field=models.CharField(choices=[('elementary', '小学生'), ('junior', '中学生'), ('high', '高校生'), ('custom', '金額自由設定')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='reward_per_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='１コマ当たりの報酬額'),
        ),
    ]
