# Generated by Django 5.2.4 on 2025-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0011_alter_rewardcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('pending', '保留'), ('confirmed', '確定'), ('cancelled', '取消')], db_index=True, default='pending', max_length=10, verbose_name='状態'),
        ),
    ]
