# Generated by Django 5.2.4 on 2025-08-19 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0012_remove_classschedule_is_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classkarte',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='RewardClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RewardClosingTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_count', models.IntegerField()),
                ('unit_reward', models.IntegerField(blank=True, null=True)),
                ('total_reward', models.IntegerField()),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='personal_info.rewardclosing')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_info.teacherprofile')),
            ],
        ),
    ]
