# Generated by Django 5.2.5 on 2025-08-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0014_downloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '担当講師割当',
                'verbose_name_plural': '担当講師割当',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='欠席'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_held',
            field=models.BooleanField(default=False, help_text='実施済'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_tardy',
            field=models.BooleanField(default=False, help_text='遅刻'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='note',
            field=models.TextField(blank=True, default='', help_text='備考/実施メモ'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['class_date', 'teacher'], name='personal_in_class_d_7bc633_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['class_date', 'student'], name='personal_in_class_d_46f3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['teacher', 'class_date', 'start_time'], name='personal_in_teacher_f3df78_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['student', 'class_date', 'start_time'], name='personal_in_student_4f141a_idx'),
        ),
        migrations.AddField(
            model_name='teacherstudentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.studentprofile'),
        ),
        migrations.AddField(
            model_name='teacherstudentassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudentassignment',
            unique_together={('teacher', 'student')},
        ),
    ]
