# Generated by Django 5.2.5 on 2025-08-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0015_accesslog'),
        ('personal_info', '0015_teacherstudentassignment_classschedule_is_absent_and_more'),
    ]

    operations = [
    ]
