# Generated by Django 5.2.5 on 2025-08-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0016_merge_20250822_0945'),
        ('personal_info', '0016_teacherstudentassignment_subjects'),
    ]

    operations = [
    ]
