# Generated by Django 5.2.5 on 2025-09-22 07:37

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_billing(apps, schema_editor):
    StudentProfile = apps.get_model("personal_info", "StudentProfile")
    for student in StudentProfile.objects.all():
        value = getattr(student, "billing_per_class", None)
        if value is not None:
            student.custom_billing_per_class = value
            student.save(update_fields=["custom_billing_per_class"])


class Migration(migrations.Migration):

    dependencies = [
        ("personal_info", "0019_auto_schedule_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("elementary", "小学生"),
                            ("junior", "中学生"),
                            ("high", "高校生"),
                            ("custom", "金額自由設定"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "fee_per_class",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="１コマ当たりの請求額"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="custom_billing_per_class",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="自由請求額（１コマ）"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="billing_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personal_info.billingcategory",
                verbose_name="請求区分（生徒向け）",
            ),
        ),
        migrations.RunPython(copy_existing_billing, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="studentprofile",
            name="billing_per_class",
        ),
    ]
